### ISSUE TITLE
How to debug wireless issues?

### ISSUE THREAD

**Issue by Algram** [ahtn/keyplus#104]
Hi there,
I managed to get my keyplus boards working in wired mode. I want to use one of the boards as the wired receiver and the other board completely wireless.

I can not get the wireless working. I tried everything the last couple hours. The RF settings and the layout should be correct:

```yaml
# Generated on 2020-06-31 at 20:06

rf_settings:
  aes_encryption_key: encryptionkey
  auto_retransmit_count: 15
  data_rate: 2mbps
  pipe0: bcf32b924c
  pipe1: 1f7b477795
  pipe2: '74'
  pipe3: ae
  pipe4: '71'
  pipe5: '00'
  rf_channel: 119
  transmit_power: 0db

```

```yaml
version: 0.3.3

devices:
  receiver:
    id: 0
    layout: receiver
    wired_split: false
    wireless_split: true
    scan_mode: # rf dongle, so don't need a matrix
      mode: pin_gnd
      pins: [
        D3
      ]
  gamepad:
    id: 1
    layout: gamepad
    wired_split: false
    wireless_split: true
    layout_offset: 0
    scan_mode:
      mode: pin_gnd
      pins: [
        D3, D2, D1, D0, A0,
        A1, A2, A3, A4, A5,
        A6, A7, B0, B1, B2,
        B3, C0, C1, C2, C3,
      ]
      # maps how keys are physically wired, to how they appear visually

layouts:
  receiver:
    layers: [
      [ # layer 0 (base)
        [
          x,
        ]
      ],
    ]
  gamepad:
    default_layer: 0
    # This layout shows how layer keys can be chained together. If L1 and
    # L2 are pressed on the base layer, then L3 is activated.
    layers: [
      [ # layer 0 (base)
        [
          esc , 1   , 2   , 3   , 4   ,
          tab , q   , w   , e   , r   ,
          lsft, a   , s   , d   , f   ,
          lctl, x   , g   , c   , spc  ,
        ]
      ],
      # [ # layer 1 (lower)
      #   [
      #     '~' , '!' , '@' , '#' , '$' , '%' , '^' , '&' , '*' , '(' , ')' , ____ ,
      #     del , F1  , F2  , F3  , F4  , F5  , F6  , '_' , '+' , '{' , '}' , '|'  ,
      #     ____, F7  , F8  , F9  , F10 , F11 , F12 , iso~, iso|, home, end , ____ ,
      #     ____, ____, ____, ____, ____, ____, ____, L3  , ____, ____, ____, ____ ,
      #   ]
      # ],
      # [ # layer 2 (raise)
      #   [
      #     '`' ,  1  ,  2  ,  3  ,  4  ,  5  ,  6  ,  7  ,  8  ,  9  ,  0  , ____ ,
      #     del , F1  , F2  , F3  , F4  , F5  , F6  , '-' , '=' , '[' , ']' , '\'  ,
      #     ____, F7  , F8  , F9  , F10 , F11 , F12 , iso#, iso|, pgup, pgdn, ____ ,
      #     ____, ____, ____, ____, L3  , ____, ____, ____, ____, ____, ____, ____ ,
      #   ]
      # ],
      # [ # layer 3 (media 'lower+raise'), press L1+L2 on base layer
      #   [
      #     ____, pscr, mply, volu, mstp, ____, wh_u, btn1, ms_u, btn2, ____, nlck ,
      #     ____, mute, mprv, vold, mnxt, app , wh_d, ms_l, ms_d, ms_r, btn3, slck ,
      #     ____, C-y , CS-z, C-i , ____, ____, ____, ____, ____, ____, ____, caps ,
      #     ____, ____, ____, ____, ____, ____, ____, ____, ____, ____, ____, ____ ,
      #   ]
      # ],
]
```

This is my schematic:
![image](https://user-images.githubusercontent.com/5053729/73578514-c4192280-4477-11ea-8b34-8a0a3b49fbb8.png)

Can someone maybe look over those and confirm if they look good?
I can also provide all the schematics for the boards I made, but they are basically the same as the keyplus_mini.

Is there any way to debug the wireless connection?
