### ISSUE TITLE
Add LED indicator support and configuration

### ISSUE THREAD

**Issue by ahtn** [ahtn/keyplus#12]
Currently the code has indicator LED's added in [the HID descriptor](https://github.com/ahtn/keyplus/blob/00024cdade3139cb93d1f3e50e95033bcf316bd0/src/usb/hid_descriptors.c#L39), but it has no way to use them yet. It would also be good if the indicator LED's can work with user define layers.

I would like indicator LED's to be easily configurable from the yaml config file. The pins on the controller would be allocated in a similar way as the row and column pins of the matrix. That is the controller would map a list of LED pins `LED0, LED1, ...` to a dedicated list of LED hardware pins on the controller `C0, C1, ...` based on the number of LED's describe in the config file.

The user would then define roles to the LEDx pins in the config file something like this for each device:

```
keyboard_device:
   # ...
   num_leds: 4
   led0: caps_lock
   led1: num_lock
   led2: kana
   led3: layer2
   # ...
```
