### ISSUE TITLE
Document how to pair wireless devices

### ISSUE THREAD

**Issue by Merlin04** [ahtn/keyplus#53]
I can't figure out how to pair my keyboard and the receiver. I see a "pair" command in the keyplus-cli, but it doesn't say how to use it. I also can't figure out how to pair my Unifying mouse with the receiver.

**Comment by Merlin04** [comment]
I figured out how to pair the mouse, but I haven't figured out the keyboard pairing.

**Comment by ahtn** [comment]
You can't wireless pair keyboards, only the mouse.  You can only 'pair' keyboards over USB. To pair them load the same RF settings to each device over USB, and give each device a unique ID.

Given hardware constraints, it would be difficult to securely transmit the encryption key using wireless, so you can only do it via USB.

**Comment by Merlin04** [comment]
I added the RF settings already, but it still doesn't work. I was wondering if there was an additional step, but it doesn't seem like it.

**Comment by ahtn** [comment]
If you have a wireless dongle, then that counts as a device, and needs a separate ID as well.
Also, you need to make sure that `wireless_split` is enabled for each device (maybe I should rename that setting to just `wireless`?).


```yaml
devices:
  first_device:
    id: 0
    wireless_split: true
    wireless_mouse: true # allows pairing Logitech mice
    # ...
  second_device:
    id: 1
    wireless_split: true
    wireless_mouse: true
    # ...

  # rf dongle
  nrf_dongle:
    id: 10
    wireless_split: true
    wireless_mouse: true
    scan_mode: # rf dongle, so don't need a matrix
       mode: no_matrix # options: col_row, pins, no_matrix
```

You need to make sure that each device has the same RF settings loaded over USB, and it should work without any other configuration.
