### ISSUE TITLE
keyplus_flasher on macOS

### ISSUE THREAD

**Issue by lightingghost** [ahtn/keyplus#82]
I am trying to use `keyplus_flasher` gui on macOS 10.13.4, but the "Connected USB devices" is not showing any device. 

Manually importing `easyhid` and enumerating devices can see the keyplus nRF24 Dongle:

```
HIDDevice:
    USB_1209_bb02_14311000 | 1209:bb02 | keyplus | nRF24 Dongle | 3bff84d7b6
    release_number: 0
    usage_page: 1
    usage: 6
    interface_number: -1
```
But the interface_number is showing `-1`, which might be the reason why it is not recognized as a keyplus device.
